# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FHmnijhg-XbiCehiX0ofmqTzKAt2ETQ2
"""

import streamlit as st
import pandas as pd
import joblib
import numpy as np

# Konfigurasi Halaman
st.set_page_config(page_title="Prediksi Kelulusan Mahasiswa", layout="centered")

# --- 1. LOAD MODEL ---
@st.cache_resource
def load_models():
    model = joblib.load('model_deploy/model_knn.pkl')
    scaler = joblib.load('model_deploy/scaler.pkl')
    le = joblib.load('model_deploy/label_encoder.pkl')
    return model, scaler, le

try:
    model, scaler, le = load_models()
except FileNotFoundError:
    st.error("File model tidak ditemukan! Pastikan folder 'model_deploy' berisi file .pkl")
    st.stop()

# --- 2. JUDUL ---
st.title("🎓 Prediksi Kelulusan Mahasiswa")
st.write("Aplikasi Intervensi Dini Akademik (Fitur: IP & SKS Semester 1-6)")
st.markdown("---")

col_id1, col_id2 = st.columns(2)
with col_id1:
    nama = st.text_input("Nama Mahasiswa")
with col_id2:
    nim = st.text_input("NIM")

st.markdown("### 📊 Input Riwayat Akademik")

# --- 3. FORM INPUT NILAI ---
col_ip, col_sks = st.columns(2)

input_ip = {}
input_sks = {}

with col_ip:
    st.subheader("Indeks Prestasi (IP)")
    for i in range(1, 7):
        input_ip[f'SMT{i}'] = st.number_input(f"IP Semester {i}", min_value=0.0, max_value=4.0, value=3.0, step=0.01)

with col_sks:
    st.subheader("SKS Lulus")
    for i in range(1, 7):
        input_sks[f'SMT{i}'] = st.number_input(f"SKS Semester {i}", min_value=0, max_value=24, value=20, step=1)

# --- 4. PREDIKSI ---
if st.button("🔍 Prediksi Status Kelulusan", type="primary"):
    if not nama or not nim:
        st.warning("Mohon lengkapi Nama dan NIM terlebih dahulu.")
    else:
        # A. Susun Data (URUTAN HARUS SAMA PERSIS DENGAN SAAT TRAINING)
        # Urutan di training: IP_1..6 lalu SKS_1..6

        data_input = {
            # Kelompok IP
            'IP_LULUS_SMT1': [input_ip['SMT1']],
            'IP_LULUS_SMT2': [input_ip['SMT2']],
            'IP_LULUS_SMT3': [input_ip['SMT3']],
            'IP_LULUS_SMT4': [input_ip['SMT4']],
            'IP_LULUS_SMT5': [input_ip['SMT5']],
            'IP_LULUS_SMT6': [input_ip['SMT6']],

            # Kelompok SKS
            'SKS_LULUS_SMT1': [input_sks['SMT1']],
            'SKS_LULUS_SMT2': [input_sks['SMT2']],
            'SKS_LULUS_SMT3': [input_sks['SMT3']],
            'SKS_LULUS_SMT4': [input_sks['SMT4']],
            'SKS_LULUS_SMT5': [input_sks['SMT5']],
            'SKS_LULUS_SMT6': [input_sks['SMT6']],
        }

        df_predict = pd.DataFrame(data_input)

        # B. Scaling
        try:
            df_scaled = scaler.transform(df_predict)
        except Exception as e:
            st.error(f"Error Scaling: {e}. Kemungkinan jumlah fitur tidak cocok (Pastikan model dilatih ulang dengan 12 fitur).")
            st.stop()

        # C. Prediksi
        prediksi_angka = model.predict(df_scaled)[0]
        probabilitas = model.predict_proba(df_scaled)[0]

        hasil_teks = le.inverse_transform([prediksi_angka])[0]

        # D. Tampilan Hasil
        st.markdown("---")
        st.subheader("Hasil Prediksi")

        if hasil_teks == "Tepat Waktu":
            st.success(f"✅ Mahasiswa diprediksi **LULUS TEPAT WAKTU**")
            st.write(f"Keyakinan Model: {probabilitas[0]*100:.1f}%")
        else:
            st.error(f"⚠️ Mahasiswa diprediksi **TERLAMBAT LULUS**")
            st.write(f"Keyakinan Model (Risiko): {probabilitas[1]*100:.1f}%")
            st.info("💡 **Saran:** Lakukan intervensi akademik segera.")